[workspace]
members = [
    "contracts/multisig_wallet",
]

[workspace.package]
version = "0.1.0"
edition = "2024_07"
authors = ["Inshell"]

[workspace.dependencies]
starknet = "2.12.0"
openzeppelin_governance = "=2.0.0"
openzeppelin_utils = "=2.0.0"
