[package]
name = "multisig_wallet"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = { workspace = true }
openzeppelin_governance = { workspace = true }
openzeppelin_utils = { workspace = true }

[dev-dependencies]
snforge_std = "^0.52.0"

[[target.starknet-contract]]
sierra = true
casm = true

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
